@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor 00FF00
skinparam titleBackgroundColor #00FF00
skinparam sequenceMessageAlign center
title AWS - Textract Process
    (*) --> "Image Ingress"
    "Image Ingress" --> "Validate Image"
    if "" then
      -right->[true] "Extract Image Data"
      if "" then
        -->[true] "Write to data storage repository"
        --> if "" then
                -->[true] "Write image summary to log"
                --> (*)
            else
                -left->[false] "Log Error"
            endif
      else
        -left->[false] "Log Error"
      endif
    else
            -left->[false] "Log Error"
            --> (*)
    endif
@enduml